### ISSUE TITLE
Updated translations should be automatically deployed

### ISSUE THREAD

**Issue by DonnchaC** [equalitie/deflect-docs#58]
Strings to translate are automatically uploaded to Transifex from the CI system. The translated strings are not automatically merged or deployed to the live site. A manual step is currently needed to run `tx pull -a` to fetch translations and commit those to the repo.

This step should be automated so that new approved translations are automatically pushed to the live docs site.

**Comment by joelanders** [comment]
So, just for the record, Transifex has [webhooks](https://docs.transifex.com/integrations/webhooks). So we'd have to run a little HTTP server somewhere that waits for Transifex to hit it, then does the `tx pull`, `git push` stuff.

Actually, it seems like someone's already written such a [server](https://www.transifex.com/blog/2015/bridging-github-and-transifex-with-txgh/), so if we want to use that it's just a matter of configuring and running it.

It's a bit of a shame Transifex can fetch things from Github but can't push things to it, so we gotta worry about running this little service...

**Comment by timball** [comment]
oh interesting ... this server only needs to be stood up during compile time right? aka it can be ephemeral and be turned into a "function-as-a-service" type thing? 

--timball

**Comment by demkodo** [comment]
Maybe a dumb remark / question, but can we set rules for when the pull from Transifex takes place? As translations need to be reviewed first. Only when that is done, the strings can be fetched and pushed to GitHub. (Referring to [the page](https://www.transifex.com/blog/2015/bridging-github-and-transifex-with-txgh/) Joe pointed out).

**Comment by demkodo** [comment]
I'm getting ahead of myself :)

**Comment by timball** [comment]
this might be a perfect thing for the heroku free https://www.heroku.com/pricing tier since Txgh is ready for dyno deployment.

--timball

**Comment by joelanders** [comment]
```
#!/bin/bash
set -e

git fetch
branchname=$(date '+%Y.%m.%d.%H.%M')
git checkout -b $branchname
git reset --hard origin/master
tx pull --force # pull every file + language from transifex, ignoring timestamps

(cd locale &&
	for d in *; do
		git add $d
		git commit -m "$d" || true
	done
)

git push originssh/$branchname
```
Ok, we tried the txgh server and it doesn't seem to fit our use case all that well. We'd rather sync all strings unconditionally once per day rather than try to be clever and only sync resources which have become 100% translated. I wrote this little script^ a while back which I think is suitable for running under cron somewhere (we gotta make sure it has git + tx credentials, though).

**Comment by MarkMangoba** [comment]
deployed the script to our instance on Digital Ocean.
